### ISSUE TITLE
This package causes weird tab reordering issues

### ISSUE THREAD

**Issue by sbrl** [jerone/atom-new-tab#4]
Enabling this package causes strange tab reordering issues. Here's an animated gif to show you what I mean:

![gif](http://i.imgur.com/Fow1yyo.gif)

Originally I filed this against atom/tabs (see atom/tabs#245), but they directed me to [package-cop](https://atom.io/packages/package-cop), which helped me narrow down tha it was this package that is causing my problem.

Here's a link to my settings:

https://gist.github.com/sbrl/85cf891cc52543567204

**Comment by jerone** [comment]
New version published :ship:. This should hopefully be fixed now.

**Comment by sbrl** [comment]
Thanks! That did the trick :smiley:
