### ISSUE TITLE
Button symbol is partially hidden when tab sizing is set to minimum width mode

### ISSUE THREAD

**Issue by jackbrockley** [jerone/atom-new-tab#6]
> Atom 1.10.2
> one-light-ui 1.5.0
> one-dark-ui 1.5.0
- Set UI theme to One Light or One Dark (not sure if any other themes have tab sizing options)
- Set Tab Sizing to Minimum

New tab button plus symbol appears to be partially hidden.

**Comment by jerone** [comment]
Thanks for reporting. New version :ship:ed.

**Comment by jackbrockley** [comment]
Thanks for looking at it. The icon is still slightly hidden for me:

![New tab button](http://imgur.com/jyRWG14.png)

Are you seeing it differently?

Dropping each margin to `1.0em` seems to fix it.

**Comment by jerone** [comment]
:sheep:
