### ISSUE TITLE
No + sign indicator on Atom Material Theme

### ISSUE THREAD

**Issue by Gunny123** [jerone/atom-new-tab#7]
Hi, 

I cannot get the + sign to show up using the latest versions of Material Theme and Material syntax. 

Here is a video of the issue: https://gfycat.com/HeartyGlaringAplomadofalcon

macOS: Sierra 10.12.2
Atom version: 1.12.9

**Comment by jerone** [comment]
I've actually not used Atom for a few weeks now. Maybe you can figure out why this isn't working anymore; I'll accept PR.

**Comment by Gunny123** [comment]
Back to Sublime Text?

I'll be honest though, I wouldn't really know where to start debugging. I'm just an amateur when it comes debugging Atom packages.

**Comment by jerone** [comment]
No, building apps in Visual Studio.

The style source for the Material Theme is [here](https://github.com/jerone/atom-new-tab/blob/master/styles/new-tab.less#L110-L139), but looking at that theme it hasn't been updated for a few weeks, so it could also be an Atom update.

Seeing your screencast, it looks indeed like a style issue, not a code issue.

**Comment by Gunny123** [comment]
I'll pop the hood and poke around. See if I can get it to show.

**Comment by jerone** [comment]
_Closing as inactive for 6 months..._
